/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorksIndexImport } from './routes/works.index'
import { Route as WorksWorkIdImport } from './routes/works.$workId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const WorksIndexRoute = WorksIndexImport.update({
  path: '/works/',
  getParentRoute: () => rootRoute,
} as any)

const WorksWorkIdRoute = WorksWorkIdImport.update({
  path: '/works/$workId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/works/$workId': {
      id: '/works/$workId'
      path: '/works/$workId'
      fullPath: '/works/$workId'
      preLoaderRoute: typeof WorksWorkIdImport
      parentRoute: typeof rootRoute
    }
    '/works/': {
      id: '/works/'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/works': typeof WorksIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/works': typeof WorksIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/works/$workId': typeof WorksWorkIdRoute
  '/works/': typeof WorksIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/works/$workId' | '/works'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/works/$workId' | '/works'
  id: '__root__' | '/' | '/works/$workId' | '/works/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  WorksWorkIdRoute: typeof WorksWorkIdRoute
  WorksIndexRoute: typeof WorksIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  WorksWorkIdRoute: WorksWorkIdRoute,
  WorksIndexRoute: WorksIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/works/$workId",
        "/works/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/works/$workId": {
      "filePath": "works.$workId.tsx"
    },
    "/works/": {
      "filePath": "works.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
